### ISSUE TITLE
Bug: Automatic WebSocket Reconnection Between Frontend and Backend

### ISSUE THREAD

**Issue by timon-schelling** [ItsEthra/typst-live#13]
Requesting the implementation of automatic reconnection for WebSocket connections between the frontend and backend. This feature would help maintain a stable connection and improve user experience by reducing manual reconnection needs during drops or interruptions.

**Comment by ItsEthra** [comment]
This is more of a bug than a feature request. I tried in the past to do reconnecting when connection is lost but js is acting weird so for now I'll leave it as is.

**Comment by timon-schelling** [comment]
I'll look into it, if I find the time. :)
