### ISSUE TITLE
Error on macOS

### ISSUE THREAD

**Issue by beeb** [ItsEthra/typst-live#2]
The server starts fine but after the first edit I see the following error:

```
ERROR typst_live::routes: Failed to send message to the client: Error { inner: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }) }
```

**Comment by ItsEthra** [comment]
It means that server upgraded to websocket connection but failed to send message to the client. If you can provide more information like browser and console logs I might be able to see what the issue is.

**Comment by beeb** [comment]
Doesn't happen with the new `-R` option, maybe it was a conflict with the VSCode extension
