### ISSUE TITLE
Running two instances seems fine, but is not.

### ISSUE THREAD

**Issue by haennes** [ItsEthra/typst-live#20]
First of all: great simple software.
I am having just one minor inconvenience:
When one instance is already running, and I am trying to start another one there are two problems:
1. When in the same directory it complains about `output.pdf` already existing
2. When running in a different directory it seems to work fine at a first glance, but:
   The server fails to bind to the port (which is immediately printed to and cleared from the console), suggesting everything is fine,
   while only the previous instance is accessible on localhost:5999
 
Suggestions on how to fix it:
1. Is creating the `output.pdf` in a tmp folder a bad idea?
    Should typst-live even create an output.pdf or can this be hidden behind a cmd option? For my part I only use it as a previewer only.
    This can actually interfere with file syncing, as changes to output.pdf might keep getting synced, inflating the number of versions
    To implement this feature ([this lib](https://crates.io/crates/temp-dir)) could be used
2. Could typst-live just search for the next open port and bind to that? 
    Maybe searching [these ports](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Dynamic,_private_or_ephemeral_ports) first
    This could again be hidden behind another cmd option

**Comment by ItsEthra** [comment]
There was an option to use a different port with `--port` argument but I changed it so now it looks for an open port if default is not available. See [CHANGELOG.md](https://github.com/ItsEthra/typst-live/blob/master/CHANGELOG.md)
