### ISSUE TITLE
Suggestion: add flag to avoid running the typst command

### ISSUE THREAD

**Issue by beeb** [ItsEthra/typst-live#4]
I would like to use this tool together with the [VSCode extension](https://github.com/nvarner/typst-lsp/) which does the compilation and watching already. I would only need this tool for the webserver with auto-refresh.

Would it be possible to add an option to only monitor for file changes but not run typst in the background?

In this case, one could pass the path to the PDF file instead of the source file.

**Comment by ItsEthra** [comment]
Implemented it, it should work now using `-R <pdfname>`

**Comment by beeb** [comment]
Thanks!
