### ISSUE TITLE
Open failing should not cause typst-live to fail

### ISSUE THREAD

**Issue by apeschar** [ItsEthra/typst-live#9]
On Linux, if `xdg-open` is missing, it breaks `typst-live` with a "file not found" error on this line.

~~~console
% typst-live main.typ
[INFO] Server is listening on http://127.0.0.1:5599/
Error: No such file or directory (os error 2)

Location:
    src/main.rs:43:5
~~~

https://github.com/ItsEthra/typst-live/blob/e1fbaff9259c94d9bb16c2e8184e1293e69406ab/src/main.rs#L43C12-L43C12

If I figure out how to handle errors in Rust, I'll make my own PR. If I don't get around to it, perhaps you'd like to give it a go.

**Comment by ItsEthra** [comment]
What would be the other way to open a link without `xdg-open`?

**Comment by apeschar** [comment]
So in the end: I think we should just log and ignore the error.

**Comment by ItsEthra** [comment]
Sure, if you want to make a pr that just ignores the error. Just remove `?` to avoid propagating the error on the line and discard the result using `_ = ...` to avoid unhandled result warning.
